# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/dev/EricProjects/DigitalD43/Forms/Controls.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Controls(object):
    def setupUi(self, Controls):
        Controls.setObjectName("Controls")
        Controls.resize(672, 732)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Controls.sizePolicy().hasHeightForWidth())
        Controls.setSizePolicy(sizePolicy)
        self.gridLayout_6 = QtWidgets.QGridLayout(Controls)
        self.gridLayout_6.setContentsMargins(10, 10, 10, 10)
        self.gridLayout_6.setSpacing(10)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.layoutScope = QtWidgets.QGridLayout()
        self.layoutScope.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.layoutScope.setContentsMargins(10, 10, 10, 10)
        self.layoutScope.setObjectName("layoutScope")
        self.layoutDisplay = QtWidgets.QGridLayout()
        self.layoutDisplay.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.layoutDisplay.setContentsMargins(0, 0, 0, 0)
        self.layoutDisplay.setHorizontalSpacing(0)
        self.layoutDisplay.setObjectName("layoutDisplay")
        self.widgetLiveView = WebCamView(Controls)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widgetLiveView.sizePolicy().hasHeightForWidth())
        self.widgetLiveView.setSizePolicy(sizePolicy)
        self.widgetLiveView.setMinimumSize(QtCore.QSize(50, 50))
        self.widgetLiveView.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.widgetLiveView.setObjectName("widgetLiveView")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.widgetLiveView)
        self.gridLayout_7.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setSpacing(0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.widgetDigitizedView = DigitizerView(self.widgetLiveView)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widgetDigitizedView.sizePolicy().hasHeightForWidth())
        self.widgetDigitizedView.setSizePolicy(sizePolicy)
        self.widgetDigitizedView.setMinimumSize(QtCore.QSize(50, 50))
        self.widgetDigitizedView.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.widgetDigitizedView.setObjectName("widgetDigitizedView")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.widgetDigitizedView)
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setHorizontalSpacing(0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.widgetGridView = Grid(self.widgetDigitizedView)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widgetGridView.sizePolicy().hasHeightForWidth())
        self.widgetGridView.setSizePolicy(sizePolicy)
        self.widgetGridView.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.widgetGridView.setObjectName("widgetGridView")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.widgetGridView)
        self.gridLayout_9.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_9.setHorizontalSpacing(0)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.widgetCursorView = QtWidgets.QWidget(self.widgetGridView)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widgetCursorView.sizePolicy().hasHeightForWidth())
        self.widgetCursorView.setSizePolicy(sizePolicy)
        self.widgetCursorView.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.widgetCursorView.setObjectName("widgetCursorView")
        self.gridLayout_9.addWidget(self.widgetCursorView, 0, 0, 1, 1)
        self.gridLayout_8.addWidget(self.widgetGridView, 0, 0, 1, 1)
        self.gridLayout_7.addWidget(self.widgetDigitizedView, 0, 0, 1, 1)
        self.layoutDisplay.addWidget(self.widgetLiveView, 0, 0, 1, 1)
        self.groupBoxMeasurements = QtWidgets.QGroupBox(Controls)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBoxMeasurements.sizePolicy().hasHeightForWidth())
        self.groupBoxMeasurements.setSizePolicy(sizePolicy)
        self.groupBoxMeasurements.setTitle("")
        self.groupBoxMeasurements.setFlat(True)
        self.groupBoxMeasurements.setObjectName("groupBoxMeasurements")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.groupBoxMeasurements)
        self.gridLayout_11.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.gridLayout_11.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_11.setHorizontalSpacing(0)
        self.gridLayout_11.setVerticalSpacing(6)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.groupBoxTime = QtWidgets.QGroupBox(self.groupBoxMeasurements)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBoxTime.sizePolicy().hasHeightForWidth())
        self.groupBoxTime.setSizePolicy(sizePolicy)
        self.groupBoxTime.setTitle("")
        self.groupBoxTime.setFlat(True)
        self.groupBoxTime.setObjectName("groupBoxTime")
        self.formLayout_2 = QtWidgets.QFormLayout(self.groupBoxTime)
        self.formLayout_2.setLabelAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.formLayout_2.setObjectName("formLayout_2")
        self.labelDeltaT = QtWidgets.QLabel(self.groupBoxTime)
        self.labelDeltaT.setObjectName("labelDeltaT")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.labelDeltaT)
        self.labelDeltaTDisplay = QtWidgets.QLabel(self.groupBoxTime)
        self.labelDeltaTDisplay.setObjectName("labelDeltaTDisplay")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.labelDeltaTDisplay)
        self.labelTInverse = QtWidgets.QLabel(self.groupBoxTime)
        self.labelTInverse.setObjectName("labelTInverse")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.labelTInverse)
        self.labelTInverseDisplay = QtWidgets.QLabel(self.groupBoxTime)
        self.labelTInverseDisplay.setObjectName("labelTInverseDisplay")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.labelTInverseDisplay)
        self.labelF = QtWidgets.QLabel(self.groupBoxTime)
        self.labelF.setObjectName("labelF")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.labelF)
        self.labelFDisplay = QtWidgets.QLabel(self.groupBoxTime)
        self.labelFDisplay.setObjectName("labelFDisplay")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.labelFDisplay)
        self.gridLayout_11.addWidget(self.groupBoxTime, 0, 0, 1, 1)
        self.groupBoxVoltage = QtWidgets.QGroupBox(self.groupBoxMeasurements)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBoxVoltage.sizePolicy().hasHeightForWidth())
        self.groupBoxVoltage.setSizePolicy(sizePolicy)
        self.groupBoxVoltage.setTitle("")
        self.groupBoxVoltage.setFlat(True)
        self.groupBoxVoltage.setObjectName("groupBoxVoltage")
        self.formLayout = QtWidgets.QFormLayout(self.groupBoxVoltage)
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.formLayout.setObjectName("formLayout")
        self.labelVpp = QtWidgets.QLabel(self.groupBoxVoltage)
        self.labelVpp.setObjectName("labelVpp")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.labelVpp)
        self.labelVppDisplay = QtWidgets.QLabel(self.groupBoxVoltage)
        self.labelVppDisplay.setObjectName("labelVppDisplay")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.labelVppDisplay)
        self.gridLayout_11.addWidget(self.groupBoxVoltage, 0, 1, 1, 1)
        self.layoutDisplay.addWidget(self.groupBoxMeasurements, 1, 0, 1, 1)
        self.layoutScope.addLayout(self.layoutDisplay, 0, 0, 1, 1)
        self.layoutControls = QtWidgets.QGridLayout()
        self.layoutControls.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.layoutControls.setContentsMargins(10, 10, 10, 10)
        self.layoutControls.setObjectName("layoutControls")
        self.groupBoxSettings = QtWidgets.QGroupBox(Controls)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBoxSettings.sizePolicy().hasHeightForWidth())
        self.groupBoxSettings.setSizePolicy(sizePolicy)
        self.groupBoxSettings.setObjectName("groupBoxSettings")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBoxSettings)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.comboBoxTimeBase = QtWidgets.QComboBox(self.groupBoxSettings)
        self.comboBoxTimeBase.setObjectName("comboBoxTimeBase")
        self.gridLayout_3.addWidget(self.comboBoxTimeBase, 0, 0, 1, 1)
        self.labelTimeBase = QtWidgets.QLabel(self.groupBoxSettings)
        self.labelTimeBase.setObjectName("labelTimeBase")
        self.gridLayout_3.addWidget(self.labelTimeBase, 0, 1, 1, 1)
        self.comboBoxVerticalDeflection = QtWidgets.QComboBox(self.groupBoxSettings)
        self.comboBoxVerticalDeflection.setObjectName("comboBoxVerticalDeflection")
        self.gridLayout_3.addWidget(self.comboBoxVerticalDeflection, 1, 0, 1, 1)
        self.labelVertivalDeflection = QtWidgets.QLabel(self.groupBoxSettings)
        self.labelVertivalDeflection.setObjectName("labelVertivalDeflection")
        self.gridLayout_3.addWidget(self.labelVertivalDeflection, 1, 1, 1, 1)
        self.horizontalLayoutVerticalScale = QtWidgets.QHBoxLayout()
        self.horizontalLayoutVerticalScale.setObjectName("horizontalLayoutVerticalScale")
        self.radioButtonX1 = QtWidgets.QRadioButton(self.groupBoxSettings)
        self.radioButtonX1.setObjectName("radioButtonX1")
        self.horizontalLayoutVerticalScale.addWidget(self.radioButtonX1)
        self.radioButtonX10 = QtWidgets.QRadioButton(self.groupBoxSettings)
        self.radioButtonX10.setObjectName("radioButtonX10")
        self.horizontalLayoutVerticalScale.addWidget(self.radioButtonX10)
        self.radioButtonX100 = QtWidgets.QRadioButton(self.groupBoxSettings)
        self.radioButtonX100.setObjectName("radioButtonX100")
        self.horizontalLayoutVerticalScale.addWidget(self.radioButtonX100)
        self.gridLayout_3.addLayout(self.horizontalLayoutVerticalScale, 2, 0, 1, 1)
        self.labelMultiplier = QtWidgets.QLabel(self.groupBoxSettings)
        self.labelMultiplier.setObjectName("labelMultiplier")
        self.gridLayout_3.addWidget(self.labelMultiplier, 2, 1, 1, 1)
        self.layoutControls.addWidget(self.groupBoxSettings, 0, 0, 1, 1)
        self.groupBoxMeasurement = QtWidgets.QGroupBox(Controls)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBoxMeasurement.sizePolicy().hasHeightForWidth())
        self.groupBoxMeasurement.setSizePolicy(sizePolicy)
        self.groupBoxMeasurement.setObjectName("groupBoxMeasurement")
        self.formLayout_3 = QtWidgets.QFormLayout(self.groupBoxMeasurement)
        self.formLayout_3.setObjectName("formLayout_3")
        self.spinBoxSelectedCycles = QtWidgets.QSpinBox(self.groupBoxMeasurement)
        self.spinBoxSelectedCycles.setMinimum(1)
        self.spinBoxSelectedCycles.setMaximum(20)
        self.spinBoxSelectedCycles.setProperty("value", 1)
        self.spinBoxSelectedCycles.setObjectName("spinBoxSelectedCycles")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.spinBoxSelectedCycles)
        self.labelSelectedCycles = QtWidgets.QLabel(self.groupBoxMeasurement)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelSelectedCycles.sizePolicy().hasHeightForWidth())
        self.labelSelectedCycles.setSizePolicy(sizePolicy)
        self.labelSelectedCycles.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelSelectedCycles.setObjectName("labelSelectedCycles")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.labelSelectedCycles)
        self.layoutControls.addWidget(self.groupBoxMeasurement, 1, 0, 1, 1)
        self.groupBoxView = QtWidgets.QGroupBox(Controls)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBoxView.sizePolicy().hasHeightForWidth())
        self.groupBoxView.setSizePolicy(sizePolicy)
        self.groupBoxView.setObjectName("groupBoxView")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBoxView)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.checkBoxLive = QtWidgets.QCheckBox(self.groupBoxView)
        self.checkBoxLive.setChecked(True)
        self.checkBoxLive.setObjectName("checkBoxLive")
        self.gridLayout_5.addWidget(self.checkBoxLive, 2, 0, 1, 1)
        self.checkBoxDigitizedView = QtWidgets.QCheckBox(self.groupBoxView)
        self.checkBoxDigitizedView.setObjectName("checkBoxDigitizedView")
        self.gridLayout_5.addWidget(self.checkBoxDigitizedView, 2, 1, 1, 1)
        self.radioButtonStop = QtWidgets.QRadioButton(self.groupBoxView)
        self.radioButtonStop.setObjectName("radioButtonStop")
        self.gridLayout_5.addWidget(self.radioButtonStop, 3, 0, 1, 1)
        self.radioButtonRun = QtWidgets.QRadioButton(self.groupBoxView)
        self.radioButtonRun.setObjectName("radioButtonRun")
        self.gridLayout_5.addWidget(self.radioButtonRun, 3, 1, 1, 1)
        self.layoutControls.addWidget(self.groupBoxView, 2, 0, 1, 1)
        self.groupBoxStorage = QtWidgets.QGroupBox(Controls)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBoxStorage.sizePolicy().hasHeightForWidth())
        self.groupBoxStorage.setSizePolicy(sizePolicy)
        self.groupBoxStorage.setObjectName("groupBoxStorage")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBoxStorage)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.pushButtonSnapshot = QtWidgets.QPushButton(self.groupBoxStorage)
        self.pushButtonSnapshot.setObjectName("pushButtonSnapshot")
        self.gridLayout_4.addWidget(self.pushButtonSnapshot, 0, 0, 1, 1)
        self.pushButtonDigitizedData = QtWidgets.QPushButton(self.groupBoxStorage)
        self.pushButtonDigitizedData.setObjectName("pushButtonDigitizedData")
        self.gridLayout_4.addWidget(self.pushButtonDigitizedData, 0, 1, 1, 1)
        self.layoutControls.addWidget(self.groupBoxStorage, 3, 0, 1, 1)
        self.groupBoxSetup = QtWidgets.QGroupBox(Controls)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBoxSetup.sizePolicy().hasHeightForWidth())
        self.groupBoxSetup.setSizePolicy(sizePolicy)
        self.groupBoxSetup.setObjectName("groupBoxSetup")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBoxSetup)
        self.gridLayout.setObjectName("gridLayout")
        self.checkBoxShowCalibration = QtWidgets.QCheckBox(self.groupBoxSetup)
        self.checkBoxShowCalibration.setObjectName("checkBoxShowCalibration")
        self.gridLayout.addWidget(self.checkBoxShowCalibration, 0, 0, 1, 1)
        self.comboBoxCameraSelect = QtWidgets.QComboBox(self.groupBoxSetup)
        self.comboBoxCameraSelect.setObjectName("comboBoxCameraSelect")
        self.gridLayout.addWidget(self.comboBoxCameraSelect, 0, 1, 1, 1)
        self.layoutControls.addWidget(self.groupBoxSetup, 4, 0, 1, 1)
        self.groupBoxCalibration = QtWidgets.QGroupBox(Controls)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBoxCalibration.sizePolicy().hasHeightForWidth())
        self.groupBoxCalibration.setSizePolicy(sizePolicy)
        self.groupBoxCalibration.setObjectName("groupBoxCalibration")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBoxCalibration)
        self.gridLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButtonHoroizontalDivisions = QtWidgets.QPushButton(self.groupBoxCalibration)
        self.pushButtonHoroizontalDivisions.setObjectName("pushButtonHoroizontalDivisions")
        self.gridLayout_2.addWidget(self.pushButtonHoroizontalDivisions, 1, 0, 1, 1)
        self.spinBoxHorizontalDivisions = QtWidgets.QSpinBox(self.groupBoxCalibration)
        self.spinBoxHorizontalDivisions.setMinimum(1)
        self.spinBoxHorizontalDivisions.setMaximum(15)
        self.spinBoxHorizontalDivisions.setObjectName("spinBoxHorizontalDivisions")
        self.gridLayout_2.addWidget(self.spinBoxHorizontalDivisions, 1, 1, 1, 1)
        self.pushButtonReset = QtWidgets.QPushButton(self.groupBoxCalibration)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonReset.sizePolicy().hasHeightForWidth())
        self.pushButtonReset.setSizePolicy(sizePolicy)
        self.pushButtonReset.setObjectName("pushButtonReset")
        self.gridLayout_2.addWidget(self.pushButtonReset, 0, 1, 1, 1)
        self.pushButtonCrop = QtWidgets.QPushButton(self.groupBoxCalibration)
        self.pushButtonCrop.setObjectName("pushButtonCrop")
        self.gridLayout_2.addWidget(self.pushButtonCrop, 0, 0, 1, 1)
        self.pushButtonVerticalDivisions = QtWidgets.QPushButton(self.groupBoxCalibration)
        self.pushButtonVerticalDivisions.setObjectName("pushButtonVerticalDivisions")
        self.gridLayout_2.addWidget(self.pushButtonVerticalDivisions, 2, 0, 1, 1)
        self.spinBoxVerticalDivisions = QtWidgets.QSpinBox(self.groupBoxCalibration)
        self.spinBoxVerticalDivisions.setMinimum(1)
        self.spinBoxVerticalDivisions.setMaximum(15)
        self.spinBoxVerticalDivisions.setObjectName("spinBoxVerticalDivisions")
        self.gridLayout_2.addWidget(self.spinBoxVerticalDivisions, 2, 1, 1, 1)
        self.checkBoxPassepartout = QtWidgets.QCheckBox(self.groupBoxCalibration)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBoxPassepartout.sizePolicy().hasHeightForWidth())
        self.checkBoxPassepartout.setSizePolicy(sizePolicy)
        self.checkBoxPassepartout.setObjectName("checkBoxPassepartout")
        self.gridLayout_2.addWidget(self.checkBoxPassepartout, 3, 0, 1, 1)
        self.layoutControls.addWidget(self.groupBoxCalibration, 5, 0, 1, 1)
        self.layoutScope.addLayout(self.layoutControls, 0, 1, 1, 1)
        self.gridLayout_6.addLayout(self.layoutScope, 0, 0, 1, 1)

        self.retranslateUi(Controls)
        self.checkBoxShowCalibration.toggled['bool'].connect(self.groupBoxCalibration.setVisible)
        QtCore.QMetaObject.connectSlotsByName(Controls)

    def retranslateUi(self, Controls):
        _translate = QtCore.QCoreApplication.translate
        Controls.setWindowTitle(_translate("Controls", "Form"))
        self.labelDeltaT.setText(_translate("Controls", "T"))
        self.labelDeltaTDisplay.setText(_translate("Controls", "0"))
        self.labelTInverse.setText(_translate("Controls", "1/T"))
        self.labelTInverseDisplay.setText(_translate("Controls", "0"))
        self.labelF.setText(_translate("Controls", "F"))
        self.labelFDisplay.setText(_translate("Controls", "0"))
        self.labelVpp.setText(_translate("Controls", "Vpp"))
        self.labelVppDisplay.setText(_translate("Controls", "0"))
        self.groupBoxSettings.setTitle(_translate("Controls", "Settings"))
        self.comboBoxTimeBase.setToolTip(_translate("Controls", "Seconds per centimeter"))
        self.labelTimeBase.setText(_translate("Controls", "Timebase"))
        self.labelVertivalDeflection.setText(_translate("Controls", "Vertical deflection"))
        self.radioButtonX1.setText(_translate("Controls", "&X1"))
        self.radioButtonX10.setText(_translate("Controls", "X&10"))
        self.radioButtonX100.setText(_translate("Controls", "X1&00"))
        self.labelMultiplier.setText(_translate("Controls", "Multiplier"))
        self.groupBoxMeasurement.setTitle(_translate("Controls", "Measurement"))
        self.labelSelectedCycles.setText(_translate("Controls", "Selected cycles (frequency counter)"))
        self.groupBoxView.setTitle(_translate("Controls", "View"))
        self.checkBoxLive.setText(_translate("Controls", "Live"))
        self.checkBoxDigitizedView.setText(_translate("Controls", "Digitized"))
        self.radioButtonStop.setText(_translate("Controls", "S&top"))
        self.radioButtonRun.setText(_translate("Controls", "R&un"))
        self.groupBoxStorage.setTitle(_translate("Controls", "Storage"))
        self.pushButtonSnapshot.setText(_translate("Controls", "Snapshot"))
        self.pushButtonDigitizedData.setText(_translate("Controls", "Digitized Data"))
        self.groupBoxSetup.setTitle(_translate("Controls", "Setup"))
        self.checkBoxShowCalibration.setText(_translate("Controls", "Calibrate"))
        self.groupBoxCalibration.setTitle(_translate("Controls", "Calibration"))
        self.pushButtonHoroizontalDivisions.setText(_translate("Controls", "Horizontal Divisions"))
        self.pushButtonReset.setText(_translate("Controls", "Reset"))
        self.pushButtonCrop.setText(_translate("Controls", "Crop"))
        self.pushButtonVerticalDivisions.setText(_translate("Controls", "Vertical Divisions"))
        self.checkBoxPassepartout.setText(_translate("Controls", "Passepartout"))

from Forms.DigitizerView import DigitizerView
from Forms.Grid import Grid
from Forms.WebCamView import WebCamView

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Controls = QtWidgets.QWidget()
    ui = Ui_Controls()
    ui.setupUi(Controls)
    Controls.show()
    sys.exit(app.exec_())

